### ISSUE TITLE
使用readme 里的docker 镜像跑LLMPreProj 这个工程,会报这个错误呢，辛苦帮忙看啥为啥呢？

### ISSUE THREAD

**Issue by ldh127** [liucongg/ChatGPTBook#6]
[2023-10-08 14:58:00,215] [INFO] [launch.py:162:main] dist_world_size=1
[2023-10-08 14:58:00,215] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0
[2023-10-08 14:58:01,975] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
> initializing model parallel with size 1
Traceback (most recent call last):
  File "pretrain_model.py", line 694, in <module>
    main()
  File "pretrain_model.py", line 644, in main
    initialize_distributed(args)
  File "pretrain_model.py", line 113, in initialize_distributed
    set_deepspeed_activation_checkpointing(args)
  File "pretrain_model.py", line 73, in set_deepspeed_activation_checkpointing
    deepspeed.checkpointing.configure(mpu, deepspeed_config=args.deepspeed_config, num_checkpoints=args.num_layers)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 887, in configure
    _configure_using_config_file(deepspeed_config, mpu=mpu)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 804, in _configure_using_config_file
    config = DeepSpeedConfig(config, mpu=mpu).activation_checkpointing_config
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/config.py", line 728, in __init__
    config_decoded = base64.urlsafe_b64decode(config.strip()).decode('utf-8')
  File "/opt/conda/lib/python3.8/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/opt/conda/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
[2023-10-08 14:58:03,235] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 1179
[2023-10-08 14:58:03,236] [ERROR] [launch.py:324:sigkill_handler] ['/opt/conda/bin/python', '-u', 'pretrain_model.py', '--local_rank=0'] exits with return code = 1

**Comment by ldh127** [comment]
我理解的是docker 里的环境应该是直接可以跑这个版本的呀？
